name: Sync to Hugging Face hub

on:
  push:
    branches: [main]        # Trigger only on main branch changes
  workflow_dispatch:         # Allow manual trigger from GitHub Actions tab

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout GitHub repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0     # Important: fetch full history to avoid rebase issues
          lfs: true          # If you use large files

      - name: Set up Git identity
        run: |
          git config --global user.email "bh2ggsipu@gmail.com"
          git config --global user.name "SachdevaVansh"

      - name: Add Hugging Face remote and rebase
        run: |
          git remote add hf https://SachdevaVansh:${{ secrets.HF_TOKEN }}@huggingface.co/spaces/SachdevaVansh/Search_Engine_LLM
          git fetch hf
          git rebase hf/main

      - name: Push to Hugging Face
        run: git push hf main
