name: Sync to Hugging Face hub

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          lfs: true
          fetch-depth: 0

      - name: Setup Git identity
        run: |
          git config --global user.email "bh2ggsipu@gmail.com"
          git config --global user.name "SachdevaVansh"

      - name: Push to Hugging Face (force)
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: git push https://SachdevaVansh:${HF_TOKEN}@huggingface.co/spaces/SachdevaVansh/Search_Engine_LLM main --force
