name: Sync to Hugging Face hub

on:
  push:
    branches: [main]

  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true

      - name: Set up Git
        run: |
          git config --global user.email "you@example.com"
          git config --global user.name "Your Name"

      - name: Add Hugging Face remote
        run: |
          git remote add hf https://SachdevaVansh:${{ secrets.HF_TOKEN }}@huggingface.co/spaces/SachdevaVansh/Search_Engine_LLM
          git fetch hf
          git rebase hf/main

      - name: Push to Hugging Face
        run: git push hf main
